[RabbitMQ]
# RabbitMQ配置
# 具体信息可询问平台部署MQ相关同事，对MQ服务的地址，端口，登录用户名和密码按照实际填写即可。
addr=192.168.30.138
port=2000
username=guest
password=guest

[Host]
# 查看驾驶舱主机ip和mac地址进行填写，注意，mac地址需要与平台注册驾驶舱所填mac一致，否则无法与平台完成鉴权。
ip=
mac=

[Cabin]
# 油门踏板无踩踏值（也就是油门踏板悬空时的值）
# 当悬空油门踏板时，通过实时查看control.txt日志中的“油门:”后的数字，就是悬空油门踏板的实际值
# 实际填写时，建议填写比实际值更大的值，这里可以理解为，如果实际值为260，可以填写为270或者280，从而避免自检时踏板初始有值的情况。
# 后续填写最小值或最大值时为同样原因，不再详细解释
acceleratorMin=0

# 油门踩死后的值，实际填写时，建议比实际值更小，这里可以理解为，如果实际值为830，可以填写为820
# 后续填写最小值或最大值时为同样原因，不再详细解释
acceleratorMax=100


# 离合踏板（电制动）无踩踏值（也就是离合踏板悬空时的值）
# 通过实时查看control.txt日志中的“离合:”后的数字，就是离合踏板的实际值
electricBrakeMin=0

# 离合踏板踩死后的值
electricBrakeMax=100


# 刹车踏板（机械制动）无踩踏值，也就是悬空时的值
# 通过实时查看control.txt日志中的“刹车:”后的数字，就是刹车踏板的实际值
hydraulicBrakeMin=0

# 刹车踏板踩死后的值
hydraulicBrakeMax=100


# 方向盘左打死值，建议比实际值更小。
# 通过实时查看control.txt日志中的“方向盘:”后的数字，就是刹车踏板的实际值
steeringwheelLeftMax=-450

# 方向盘打正值，这里是为了矫正方向盘打正的值，因为驾驶舱出场时方向盘可能会有一个左偏或者右偏的小误差。
# 根据实际值打正后的值填写，无需更小或者更大。
steeringwheelMedian=0

# 方向盘右转最小值，用力右打死，用来判断方向盘左转还是右转，故填写时，建议要比实际值小。
steeringwheelRightMin=450

# 方向盘右打死实际值，此值为右打死临界值，也就是说，从这一刻开始，再往右打都认为是右打死，方便无需用力即可右打死，建议实际值更大点。
steeringwheelRightOffset=450


# 手刹最小值，手刹拉上去为最小。
# 通过实时查看control.txt日志中的“手刹:”后的数字，就是手刹的实际值
# 手刹有效为总行程的80%以上。其他视为手刹无效（相当于没有拉）。
hardBrakeMin=0

# 手刹最大值，手刹放下为最大。
hardBrakeMax=1

