// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_H_

#include "flatbuffers/flatbuffers.h"

struct Ping;
struct PingBuilder;
struct PingT;

struct Pong;
struct PongBuilder;
struct PongT;

bool operator==(const PingT &lhs, const PingT &rhs);
bool operator!=(const PingT &lhs, const PingT &rhs);
bool operator==(const PongT &lhs, const PongT &rhs);
bool operator!=(const PongT &lhs, const PongT &rhs);

inline const flatbuffers::TypeTable *PingTypeTable();

inline const flatbuffers::TypeTable *PongTypeTable();

enum CommonResult : uint8_t {
  CommonResult_Fail = 0,
  CommonResult_Success = 1,
  CommonResult_MIN = CommonResult_Fail,
  CommonResult_MAX = CommonResult_Success
};

inline const CommonResult (&EnumValuesCommonResult())[2] {
  static const CommonResult values[] = {
    CommonResult_Fail,
    CommonResult_Success
  };
  return values;
}

inline const char * const *EnumNamesCommonResult() {
  static const char * const names[3] = {
    "Fail",
    "Success",
    nullptr
  };
  return names;
}

inline const char *EnumNameCommonResult(CommonResult e) {
  if (flatbuffers::IsOutRange(e, CommonResult_Fail, CommonResult_Success)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCommonResult()[index];
}

enum LightAction : uint8_t {
  LightAction_TrunOff = 0,
  LightAction_TrunOn = 1,
  LightAction_MIN = LightAction_TrunOff,
  LightAction_MAX = LightAction_TrunOn
};

inline const LightAction (&EnumValuesLightAction())[2] {
  static const LightAction values[] = {
    LightAction_TrunOff,
    LightAction_TrunOn
  };
  return values;
}

inline const char * const *EnumNamesLightAction() {
  static const char * const names[3] = {
    "TrunOff",
    "TrunOn",
    nullptr
  };
  return names;
}

inline const char *EnumNameLightAction(LightAction e) {
  if (flatbuffers::IsOutRange(e, LightAction_TrunOff, LightAction_TrunOn)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLightAction()[index];
}

enum RcdControlCmd : uint8_t {
  RcdControlCmd_Unknow = 0,
  RcdControlCmd_Start = 1,
  RcdControlCmd_Finish = 2,
  RcdControlCmd_MIN = RcdControlCmd_Unknow,
  RcdControlCmd_MAX = RcdControlCmd_Finish
};

inline const RcdControlCmd (&EnumValuesRcdControlCmd())[3] {
  static const RcdControlCmd values[] = {
    RcdControlCmd_Unknow,
    RcdControlCmd_Start,
    RcdControlCmd_Finish
  };
  return values;
}

inline const char * const *EnumNamesRcdControlCmd() {
  static const char * const names[4] = {
    "Unknow",
    "Start",
    "Finish",
    nullptr
  };
  return names;
}

inline const char *EnumNameRcdControlCmd(RcdControlCmd e) {
  if (flatbuffers::IsOutRange(e, RcdControlCmd_Unknow, RcdControlCmd_Finish)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRcdControlCmd()[index];
}

enum RcdControlCmdResult : uint8_t {
  RcdControlCmdResult_Unknow = 0,
  RcdControlCmdResult_Accept = 2,
  RcdControlCmdResult_Reject = 4,
  RcdControlCmdResult_MIN = RcdControlCmdResult_Unknow,
  RcdControlCmdResult_MAX = RcdControlCmdResult_Reject
};

inline const RcdControlCmdResult (&EnumValuesRcdControlCmdResult())[3] {
  static const RcdControlCmdResult values[] = {
    RcdControlCmdResult_Unknow,
    RcdControlCmdResult_Accept,
    RcdControlCmdResult_Reject
  };
  return values;
}

inline const char * const *EnumNamesRcdControlCmdResult() {
  static const char * const names[6] = {
    "Unknow",
    "",
    "Accept",
    "",
    "Reject",
    nullptr
  };
  return names;
}

inline const char *EnumNameRcdControlCmdResult(RcdControlCmdResult e) {
  if (flatbuffers::IsOutRange(e, RcdControlCmdResult_Unknow, RcdControlCmdResult_Reject)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRcdControlCmdResult()[index];
}

enum TakeoverPurpose : uint8_t {
  TakeoverPurpose_Pullover = 0,
  TakeoverPurpose_Precisedocking = 1,
  TakeoverPurpose_Detour = 2,
  TakeoverPurpose_SpecifyTarget = 3,
  TakeoverPurpose_AutonomousDriving = 4,
  TakeoverPurpose_TryToDriving = 5,
  TakeoverPurpose_MonitorDriving = 6,
  TakeoverPurpose_MIN = TakeoverPurpose_Pullover,
  TakeoverPurpose_MAX = TakeoverPurpose_MonitorDriving
};

inline const TakeoverPurpose (&EnumValuesTakeoverPurpose())[7] {
  static const TakeoverPurpose values[] = {
    TakeoverPurpose_Pullover,
    TakeoverPurpose_Precisedocking,
    TakeoverPurpose_Detour,
    TakeoverPurpose_SpecifyTarget,
    TakeoverPurpose_AutonomousDriving,
    TakeoverPurpose_TryToDriving,
    TakeoverPurpose_MonitorDriving
  };
  return values;
}

inline const char * const *EnumNamesTakeoverPurpose() {
  static const char * const names[8] = {
    "Pullover",
    "Precisedocking",
    "Detour",
    "SpecifyTarget",
    "AutonomousDriving",
    "TryToDriving",
    "MonitorDriving",
    nullptr
  };
  return names;
}

inline const char *EnumNameTakeoverPurpose(TakeoverPurpose e) {
  if (flatbuffers::IsOutRange(e, TakeoverPurpose_Pullover, TakeoverPurpose_MonitorDriving)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTakeoverPurpose()[index];
}

enum TaskEndReason : uint8_t {
  TaskEndReason_Normal = 0,
  TaskEndReason_NetworkInterrupt = 1,
  TaskEndReason_CockpitFault = 2,
  TaskEndReason_MIN = TaskEndReason_Normal,
  TaskEndReason_MAX = TaskEndReason_CockpitFault
};

inline const TaskEndReason (&EnumValuesTaskEndReason())[3] {
  static const TaskEndReason values[] = {
    TaskEndReason_Normal,
    TaskEndReason_NetworkInterrupt,
    TaskEndReason_CockpitFault
  };
  return values;
}

inline const char * const *EnumNamesTaskEndReason() {
  static const char * const names[4] = {
    "Normal",
    "NetworkInterrupt",
    "CockpitFault",
    nullptr
  };
  return names;
}

inline const char *EnumNameTaskEndReason(TaskEndReason e) {
  if (flatbuffers::IsOutRange(e, TaskEndReason_Normal, TaskEndReason_CockpitFault)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTaskEndReason()[index];
}

struct PingT : public flatbuffers::NativeTable {
  typedef Ping TableType;
  uint64_t timestamps = 0;
};

inline bool operator==(const PingT &lhs, const PingT &rhs) {
  return
      (lhs.timestamps == rhs.timestamps);
}

inline bool operator!=(const PingT &lhs, const PingT &rhs) {
    return !(lhs == rhs);
}


struct Ping FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PingT NativeTableType;
  typedef PingBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return PingTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMPS = 4
  };
  uint64_t timestamps() const {
    return GetField<uint64_t>(VT_TIMESTAMPS, 0);
  }
  bool mutate_timestamps(uint64_t _timestamps) {
    return SetField<uint64_t>(VT_TIMESTAMPS, _timestamps, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMPS) &&
           verifier.EndTable();
  }
  PingT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PingT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Ping> Pack(flatbuffers::FlatBufferBuilder &_fbb, const PingT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PingBuilder {
  typedef Ping Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamps(uint64_t timestamps) {
    fbb_.AddElement<uint64_t>(Ping::VT_TIMESTAMPS, timestamps, 0);
  }
  explicit PingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Ping> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Ping>(end);
    return o;
  }
};

inline flatbuffers::Offset<Ping> CreatePing(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamps = 0) {
  PingBuilder builder_(_fbb);
  builder_.add_timestamps(timestamps);
  return builder_.Finish();
}

flatbuffers::Offset<Ping> CreatePing(flatbuffers::FlatBufferBuilder &_fbb, const PingT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PongT : public flatbuffers::NativeTable {
  typedef Pong TableType;
  uint64_t timestamps = 0;
};

inline bool operator==(const PongT &lhs, const PongT &rhs) {
  return
      (lhs.timestamps == rhs.timestamps);
}

inline bool operator!=(const PongT &lhs, const PongT &rhs) {
    return !(lhs == rhs);
}


struct Pong FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PongT NativeTableType;
  typedef PongBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return PongTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMPS = 4
  };
  uint64_t timestamps() const {
    return GetField<uint64_t>(VT_TIMESTAMPS, 0);
  }
  bool mutate_timestamps(uint64_t _timestamps) {
    return SetField<uint64_t>(VT_TIMESTAMPS, _timestamps, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMPS) &&
           verifier.EndTable();
  }
  PongT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PongT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Pong> Pack(flatbuffers::FlatBufferBuilder &_fbb, const PongT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PongBuilder {
  typedef Pong Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamps(uint64_t timestamps) {
    fbb_.AddElement<uint64_t>(Pong::VT_TIMESTAMPS, timestamps, 0);
  }
  explicit PongBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Pong> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Pong>(end);
    return o;
  }
};

inline flatbuffers::Offset<Pong> CreatePong(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamps = 0) {
  PongBuilder builder_(_fbb);
  builder_.add_timestamps(timestamps);
  return builder_.Finish();
}

flatbuffers::Offset<Pong> CreatePong(flatbuffers::FlatBufferBuilder &_fbb, const PongT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PingT *Ping::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PingT>(new PingT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Ping::UnPackTo(PingT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamps(); _o->timestamps = _e; }
}

inline flatbuffers::Offset<Ping> Ping::Pack(flatbuffers::FlatBufferBuilder &_fbb, const PingT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePing(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Ping> CreatePing(flatbuffers::FlatBufferBuilder &_fbb, const PingT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const PingT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamps = _o->timestamps;
  return CreatePing(
      _fbb,
      _timestamps);
}

inline PongT *Pong::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PongT>(new PongT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Pong::UnPackTo(PongT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamps(); _o->timestamps = _e; }
}

inline flatbuffers::Offset<Pong> Pong::Pack(flatbuffers::FlatBufferBuilder &_fbb, const PongT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePong(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Pong> CreatePong(flatbuffers::FlatBufferBuilder &_fbb, const PongT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const PongT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamps = _o->timestamps;
  return CreatePong(
      _fbb,
      _timestamps);
}

inline const flatbuffers::TypeTable *CommonResultTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    CommonResultTypeTable
  };
  static const char * const names[] = {
    "Fail",
    "Success"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *LightActionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    LightActionTypeTable
  };
  static const char * const names[] = {
    "TrunOff",
    "TrunOn"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *RcdControlCmdTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    RcdControlCmdTypeTable
  };
  static const char * const names[] = {
    "Unknow",
    "Start",
    "Finish"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *RcdControlCmdResultTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    RcdControlCmdResultTypeTable
  };
  static const int64_t values[] = { 0, 2, 4 };
  static const char * const names[] = {
    "Unknow",
    "Accept",
    "Reject"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *TakeoverPurposeTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    TakeoverPurposeTypeTable
  };
  static const char * const names[] = {
    "Pullover",
    "Precisedocking",
    "Detour",
    "SpecifyTarget",
    "AutonomousDriving",
    "TryToDriving",
    "MonitorDriving"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *TaskEndReasonTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    TaskEndReasonTypeTable
  };
  static const char * const names[] = {
    "Normal",
    "NetworkInterrupt",
    "CockpitFault"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *PingTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_ULONG, 0, -1 }
  };
  static const char * const names[] = {
    "timestamps"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *PongTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_ULONG, 0, -1 }
  };
  static const char * const names[] = {
    "timestamps"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

#endif  // FLATBUFFERS_GENERATED_COMMON_H_
