// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RCD_RCD_H_
#define FLATBUFFERS_GENERATED_RCD_RCD_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

namespace Rcd {

struct CtrlRawData;
struct CtrlRawDataBuilder;
struct CtrlRawDataT;

struct VehicleCtrlCmd;

struct LightCtrlCmd;

struct ControlData;
struct ControlDataBuilder;
struct ControlDataT;

struct Status;
struct StatusBuilder;
struct StatusT;

struct ReqControlCmd;
struct ReqControlCmdBuilder;
struct ReqControlCmdT;

struct ResponVehicleAuth;
struct ResponVehicleAuthBuilder;
struct ResponVehicleAuthT;

struct ResponTaskStop;
struct ResponTaskStopBuilder;
struct ResponTaskStopT;

struct SendRemoteEstop;
struct SendRemoteEstopBuilder;
struct SendRemoteEstopT;

bool operator==(const CtrlRawDataT &lhs, const CtrlRawDataT &rhs);
bool operator!=(const CtrlRawDataT &lhs, const CtrlRawDataT &rhs);
bool operator==(const VehicleCtrlCmd &lhs, const VehicleCtrlCmd &rhs);
bool operator!=(const VehicleCtrlCmd &lhs, const VehicleCtrlCmd &rhs);
bool operator==(const LightCtrlCmd &lhs, const LightCtrlCmd &rhs);
bool operator!=(const LightCtrlCmd &lhs, const LightCtrlCmd &rhs);
bool operator==(const ControlDataT &lhs, const ControlDataT &rhs);
bool operator!=(const ControlDataT &lhs, const ControlDataT &rhs);
bool operator==(const StatusT &lhs, const StatusT &rhs);
bool operator!=(const StatusT &lhs, const StatusT &rhs);
bool operator==(const ReqControlCmdT &lhs, const ReqControlCmdT &rhs);
bool operator!=(const ReqControlCmdT &lhs, const ReqControlCmdT &rhs);
bool operator==(const ResponVehicleAuthT &lhs, const ResponVehicleAuthT &rhs);
bool operator!=(const ResponVehicleAuthT &lhs, const ResponVehicleAuthT &rhs);
bool operator==(const ResponTaskStopT &lhs, const ResponTaskStopT &rhs);
bool operator!=(const ResponTaskStopT &lhs, const ResponTaskStopT &rhs);
bool operator==(const SendRemoteEstopT &lhs, const SendRemoteEstopT &rhs);
bool operator!=(const SendRemoteEstopT &lhs, const SendRemoteEstopT &rhs);

inline const flatbuffers::TypeTable *CtrlRawDataTypeTable();

inline const flatbuffers::TypeTable *VehicleCtrlCmdTypeTable();

inline const flatbuffers::TypeTable *LightCtrlCmdTypeTable();

inline const flatbuffers::TypeTable *ControlDataTypeTable();

inline const flatbuffers::TypeTable *StatusTypeTable();

inline const flatbuffers::TypeTable *ReqControlCmdTypeTable();

inline const flatbuffers::TypeTable *ResponVehicleAuthTypeTable();

inline const flatbuffers::TypeTable *ResponTaskStopTypeTable();

inline const flatbuffers::TypeTable *SendRemoteEstopTypeTable();

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) VehicleCtrlCmd FLATBUFFERS_FINAL_CLASS {
 private:
  float steeringWheelAngle_;
  float throttlePedal_;
  float brakePedal_;
  float hydraulicBrake_;
  uint8_t retarderCtrl_;
  uint8_t exhuastBrake_;
  uint8_t parkCtrl_;
  uint8_t bucketCtrl_;
  uint8_t shiftCtrl_;
  uint8_t eStop_;
  uint8_t loadingCtrl_;
  int8_t padding0__;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return VehicleCtrlCmdTypeTable();
  }
  VehicleCtrlCmd()
      : steeringWheelAngle_(0),
        throttlePedal_(0),
        brakePedal_(0),
        hydraulicBrake_(0),
        retarderCtrl_(0),
        exhuastBrake_(0),
        parkCtrl_(0),
        bucketCtrl_(0),
        shiftCtrl_(0),
        eStop_(0),
        loadingCtrl_(0),
        padding0__(0) {
    (void)padding0__;
  }
  VehicleCtrlCmd(float _steeringWheelAngle, float _throttlePedal, float _brakePedal, float _hydraulicBrake, uint8_t _retarderCtrl, uint8_t _exhuastBrake, uint8_t _parkCtrl, uint8_t _bucketCtrl, uint8_t _shiftCtrl, bool _eStop, uint8_t _loadingCtrl)
      : steeringWheelAngle_(flatbuffers::EndianScalar(_steeringWheelAngle)),
        throttlePedal_(flatbuffers::EndianScalar(_throttlePedal)),
        brakePedal_(flatbuffers::EndianScalar(_brakePedal)),
        hydraulicBrake_(flatbuffers::EndianScalar(_hydraulicBrake)),
        retarderCtrl_(flatbuffers::EndianScalar(_retarderCtrl)),
        exhuastBrake_(flatbuffers::EndianScalar(_exhuastBrake)),
        parkCtrl_(flatbuffers::EndianScalar(_parkCtrl)),
        bucketCtrl_(flatbuffers::EndianScalar(_bucketCtrl)),
        shiftCtrl_(flatbuffers::EndianScalar(_shiftCtrl)),
        eStop_(flatbuffers::EndianScalar(static_cast<uint8_t>(_eStop))),
        loadingCtrl_(flatbuffers::EndianScalar(_loadingCtrl)),
        padding0__(0) {
    (void)padding0__;
  }
  float steeringWheelAngle() const {
    return flatbuffers::EndianScalar(steeringWheelAngle_);
  }
  void mutate_steeringWheelAngle(float _steeringWheelAngle) {
    flatbuffers::WriteScalar(&steeringWheelAngle_, _steeringWheelAngle);
  }
  float throttlePedal() const {
    return flatbuffers::EndianScalar(throttlePedal_);
  }
  void mutate_throttlePedal(float _throttlePedal) {
    flatbuffers::WriteScalar(&throttlePedal_, _throttlePedal);
  }
  float brakePedal() const {
    return flatbuffers::EndianScalar(brakePedal_);
  }
  void mutate_brakePedal(float _brakePedal) {
    flatbuffers::WriteScalar(&brakePedal_, _brakePedal);
  }
  float hydraulicBrake() const {
    return flatbuffers::EndianScalar(hydraulicBrake_);
  }
  void mutate_hydraulicBrake(float _hydraulicBrake) {
    flatbuffers::WriteScalar(&hydraulicBrake_, _hydraulicBrake);
  }
  uint8_t retarderCtrl() const {
    return flatbuffers::EndianScalar(retarderCtrl_);
  }
  void mutate_retarderCtrl(uint8_t _retarderCtrl) {
    flatbuffers::WriteScalar(&retarderCtrl_, _retarderCtrl);
  }
  uint8_t exhuastBrake() const {
    return flatbuffers::EndianScalar(exhuastBrake_);
  }
  void mutate_exhuastBrake(uint8_t _exhuastBrake) {
    flatbuffers::WriteScalar(&exhuastBrake_, _exhuastBrake);
  }
  uint8_t parkCtrl() const {
    return flatbuffers::EndianScalar(parkCtrl_);
  }
  void mutate_parkCtrl(uint8_t _parkCtrl) {
    flatbuffers::WriteScalar(&parkCtrl_, _parkCtrl);
  }
  uint8_t bucketCtrl() const {
    return flatbuffers::EndianScalar(bucketCtrl_);
  }
  void mutate_bucketCtrl(uint8_t _bucketCtrl) {
    flatbuffers::WriteScalar(&bucketCtrl_, _bucketCtrl);
  }
  uint8_t shiftCtrl() const {
    return flatbuffers::EndianScalar(shiftCtrl_);
  }
  void mutate_shiftCtrl(uint8_t _shiftCtrl) {
    flatbuffers::WriteScalar(&shiftCtrl_, _shiftCtrl);
  }
  bool eStop() const {
    return flatbuffers::EndianScalar(eStop_) != 0;
  }
  void mutate_eStop(bool _eStop) {
    flatbuffers::WriteScalar(&eStop_, static_cast<uint8_t>(_eStop));
  }
  uint8_t loadingCtrl() const {
    return flatbuffers::EndianScalar(loadingCtrl_);
  }
  void mutate_loadingCtrl(uint8_t _loadingCtrl) {
    flatbuffers::WriteScalar(&loadingCtrl_, _loadingCtrl);
  }
};
FLATBUFFERS_STRUCT_END(VehicleCtrlCmd, 24);

inline bool operator==(const VehicleCtrlCmd &lhs, const VehicleCtrlCmd &rhs) {
  return
      (lhs.steeringWheelAngle() == rhs.steeringWheelAngle()) &&
      (lhs.throttlePedal() == rhs.throttlePedal()) &&
      (lhs.brakePedal() == rhs.brakePedal()) &&
      (lhs.hydraulicBrake() == rhs.hydraulicBrake()) &&
      (lhs.retarderCtrl() == rhs.retarderCtrl()) &&
      (lhs.exhuastBrake() == rhs.exhuastBrake()) &&
      (lhs.parkCtrl() == rhs.parkCtrl()) &&
      (lhs.bucketCtrl() == rhs.bucketCtrl()) &&
      (lhs.shiftCtrl() == rhs.shiftCtrl()) &&
      (lhs.eStop() == rhs.eStop()) &&
      (lhs.loadingCtrl() == rhs.loadingCtrl());
}

inline bool operator!=(const VehicleCtrlCmd &lhs, const VehicleCtrlCmd &rhs) {
    return !(lhs == rhs);
}


FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) LightCtrlCmd FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t left_;
  uint8_t right_;
  uint8_t lowBeam_;
  uint8_t heighBeam_;
  uint8_t rotatingWarningLight_;
  uint8_t speaker_;
  uint8_t frontFog_;
  uint8_t frontStatus_;
  uint8_t side_;
  uint8_t rearPosition_;
  uint8_t emergency_;
  uint8_t brake_;
  uint8_t back_;
  uint8_t rearStatus_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LightCtrlCmdTypeTable();
  }
  LightCtrlCmd()
      : left_(0),
        right_(0),
        lowBeam_(0),
        heighBeam_(0),
        rotatingWarningLight_(0),
        speaker_(0),
        frontFog_(0),
        frontStatus_(0),
        side_(0),
        rearPosition_(0),
        emergency_(0),
        brake_(0),
        back_(0),
        rearStatus_(0) {
  }
  LightCtrlCmd(LightAction _left, LightAction _right, LightAction _lowBeam, LightAction _heighBeam, LightAction _rotatingWarningLight, LightAction _speaker, LightAction _frontFog, LightAction _frontStatus, LightAction _side, LightAction _rearPosition, LightAction _emergency, LightAction _brake, LightAction _back, LightAction _rearStatus)
      : left_(flatbuffers::EndianScalar(static_cast<uint8_t>(_left))),
        right_(flatbuffers::EndianScalar(static_cast<uint8_t>(_right))),
        lowBeam_(flatbuffers::EndianScalar(static_cast<uint8_t>(_lowBeam))),
        heighBeam_(flatbuffers::EndianScalar(static_cast<uint8_t>(_heighBeam))),
        rotatingWarningLight_(flatbuffers::EndianScalar(static_cast<uint8_t>(_rotatingWarningLight))),
        speaker_(flatbuffers::EndianScalar(static_cast<uint8_t>(_speaker))),
        frontFog_(flatbuffers::EndianScalar(static_cast<uint8_t>(_frontFog))),
        frontStatus_(flatbuffers::EndianScalar(static_cast<uint8_t>(_frontStatus))),
        side_(flatbuffers::EndianScalar(static_cast<uint8_t>(_side))),
        rearPosition_(flatbuffers::EndianScalar(static_cast<uint8_t>(_rearPosition))),
        emergency_(flatbuffers::EndianScalar(static_cast<uint8_t>(_emergency))),
        brake_(flatbuffers::EndianScalar(static_cast<uint8_t>(_brake))),
        back_(flatbuffers::EndianScalar(static_cast<uint8_t>(_back))),
        rearStatus_(flatbuffers::EndianScalar(static_cast<uint8_t>(_rearStatus))) {
  }
  LightAction left() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(left_));
  }
  void mutate_left(LightAction _left) {
    flatbuffers::WriteScalar(&left_, static_cast<uint8_t>(_left));
  }
  LightAction right() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(right_));
  }
  void mutate_right(LightAction _right) {
    flatbuffers::WriteScalar(&right_, static_cast<uint8_t>(_right));
  }
  LightAction lowBeam() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(lowBeam_));
  }
  void mutate_lowBeam(LightAction _lowBeam) {
    flatbuffers::WriteScalar(&lowBeam_, static_cast<uint8_t>(_lowBeam));
  }
  LightAction heighBeam() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(heighBeam_));
  }
  void mutate_heighBeam(LightAction _heighBeam) {
    flatbuffers::WriteScalar(&heighBeam_, static_cast<uint8_t>(_heighBeam));
  }
  LightAction rotatingWarningLight() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(rotatingWarningLight_));
  }
  void mutate_rotatingWarningLight(LightAction _rotatingWarningLight) {
    flatbuffers::WriteScalar(&rotatingWarningLight_, static_cast<uint8_t>(_rotatingWarningLight));
  }
  LightAction speaker() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(speaker_));
  }
  void mutate_speaker(LightAction _speaker) {
    flatbuffers::WriteScalar(&speaker_, static_cast<uint8_t>(_speaker));
  }
  LightAction frontFog() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(frontFog_));
  }
  void mutate_frontFog(LightAction _frontFog) {
    flatbuffers::WriteScalar(&frontFog_, static_cast<uint8_t>(_frontFog));
  }
  LightAction frontStatus() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(frontStatus_));
  }
  void mutate_frontStatus(LightAction _frontStatus) {
    flatbuffers::WriteScalar(&frontStatus_, static_cast<uint8_t>(_frontStatus));
  }
  LightAction side() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(side_));
  }
  void mutate_side(LightAction _side) {
    flatbuffers::WriteScalar(&side_, static_cast<uint8_t>(_side));
  }
  LightAction rearPosition() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(rearPosition_));
  }
  void mutate_rearPosition(LightAction _rearPosition) {
    flatbuffers::WriteScalar(&rearPosition_, static_cast<uint8_t>(_rearPosition));
  }
  LightAction emergency() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(emergency_));
  }
  void mutate_emergency(LightAction _emergency) {
    flatbuffers::WriteScalar(&emergency_, static_cast<uint8_t>(_emergency));
  }
  LightAction brake() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(brake_));
  }
  void mutate_brake(LightAction _brake) {
    flatbuffers::WriteScalar(&brake_, static_cast<uint8_t>(_brake));
  }
  LightAction back() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(back_));
  }
  void mutate_back(LightAction _back) {
    flatbuffers::WriteScalar(&back_, static_cast<uint8_t>(_back));
  }
  LightAction rearStatus() const {
    return static_cast<LightAction>(flatbuffers::EndianScalar(rearStatus_));
  }
  void mutate_rearStatus(LightAction _rearStatus) {
    flatbuffers::WriteScalar(&rearStatus_, static_cast<uint8_t>(_rearStatus));
  }
};
FLATBUFFERS_STRUCT_END(LightCtrlCmd, 14);

inline bool operator==(const LightCtrlCmd &lhs, const LightCtrlCmd &rhs) {
  return
      (lhs.left() == rhs.left()) &&
      (lhs.right() == rhs.right()) &&
      (lhs.lowBeam() == rhs.lowBeam()) &&
      (lhs.heighBeam() == rhs.heighBeam()) &&
      (lhs.rotatingWarningLight() == rhs.rotatingWarningLight()) &&
      (lhs.speaker() == rhs.speaker()) &&
      (lhs.frontFog() == rhs.frontFog()) &&
      (lhs.frontStatus() == rhs.frontStatus()) &&
      (lhs.side() == rhs.side()) &&
      (lhs.rearPosition() == rhs.rearPosition()) &&
      (lhs.emergency() == rhs.emergency()) &&
      (lhs.brake() == rhs.brake()) &&
      (lhs.back() == rhs.back()) &&
      (lhs.rearStatus() == rhs.rearStatus());
}

inline bool operator!=(const LightCtrlCmd &lhs, const LightCtrlCmd &rhs) {
    return !(lhs == rhs);
}


struct CtrlRawDataT : public flatbuffers::NativeTable {
  typedef CtrlRawData TableType;
  uint16_t clutch = 0;
  uint16_t brake = 0;
  uint16_t accelerator = 0;
  uint16_t handbrake = 0;
  int16_t steeringwheel = 0;
};

inline bool operator==(const CtrlRawDataT &lhs, const CtrlRawDataT &rhs) {
  return
      (lhs.clutch == rhs.clutch) &&
      (lhs.brake == rhs.brake) &&
      (lhs.accelerator == rhs.accelerator) &&
      (lhs.handbrake == rhs.handbrake) &&
      (lhs.steeringwheel == rhs.steeringwheel);
}

inline bool operator!=(const CtrlRawDataT &lhs, const CtrlRawDataT &rhs) {
    return !(lhs == rhs);
}


struct CtrlRawData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CtrlRawDataT NativeTableType;
  typedef CtrlRawDataBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CtrlRawDataTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLUTCH = 4,
    VT_BRAKE = 6,
    VT_ACCELERATOR = 8,
    VT_HANDBRAKE = 10,
    VT_STEERINGWHEEL = 12
  };
  uint16_t clutch() const {
    return GetField<uint16_t>(VT_CLUTCH, 0);
  }
  bool mutate_clutch(uint16_t _clutch) {
    return SetField<uint16_t>(VT_CLUTCH, _clutch, 0);
  }
  uint16_t brake() const {
    return GetField<uint16_t>(VT_BRAKE, 0);
  }
  bool mutate_brake(uint16_t _brake) {
    return SetField<uint16_t>(VT_BRAKE, _brake, 0);
  }
  uint16_t accelerator() const {
    return GetField<uint16_t>(VT_ACCELERATOR, 0);
  }
  bool mutate_accelerator(uint16_t _accelerator) {
    return SetField<uint16_t>(VT_ACCELERATOR, _accelerator, 0);
  }
  uint16_t handbrake() const {
    return GetField<uint16_t>(VT_HANDBRAKE, 0);
  }
  bool mutate_handbrake(uint16_t _handbrake) {
    return SetField<uint16_t>(VT_HANDBRAKE, _handbrake, 0);
  }
  int16_t steeringwheel() const {
    return GetField<int16_t>(VT_STEERINGWHEEL, 0);
  }
  bool mutate_steeringwheel(int16_t _steeringwheel) {
    return SetField<int16_t>(VT_STEERINGWHEEL, _steeringwheel, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_CLUTCH) &&
           VerifyField<uint16_t>(verifier, VT_BRAKE) &&
           VerifyField<uint16_t>(verifier, VT_ACCELERATOR) &&
           VerifyField<uint16_t>(verifier, VT_HANDBRAKE) &&
           VerifyField<int16_t>(verifier, VT_STEERINGWHEEL) &&
           verifier.EndTable();
  }
  CtrlRawDataT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CtrlRawDataT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<CtrlRawData> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CtrlRawDataT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CtrlRawDataBuilder {
  typedef CtrlRawData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_clutch(uint16_t clutch) {
    fbb_.AddElement<uint16_t>(CtrlRawData::VT_CLUTCH, clutch, 0);
  }
  void add_brake(uint16_t brake) {
    fbb_.AddElement<uint16_t>(CtrlRawData::VT_BRAKE, brake, 0);
  }
  void add_accelerator(uint16_t accelerator) {
    fbb_.AddElement<uint16_t>(CtrlRawData::VT_ACCELERATOR, accelerator, 0);
  }
  void add_handbrake(uint16_t handbrake) {
    fbb_.AddElement<uint16_t>(CtrlRawData::VT_HANDBRAKE, handbrake, 0);
  }
  void add_steeringwheel(int16_t steeringwheel) {
    fbb_.AddElement<int16_t>(CtrlRawData::VT_STEERINGWHEEL, steeringwheel, 0);
  }
  explicit CtrlRawDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CtrlRawData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CtrlRawData>(end);
    return o;
  }
};

inline flatbuffers::Offset<CtrlRawData> CreateCtrlRawData(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t clutch = 0,
    uint16_t brake = 0,
    uint16_t accelerator = 0,
    uint16_t handbrake = 0,
    int16_t steeringwheel = 0) {
  CtrlRawDataBuilder builder_(_fbb);
  builder_.add_steeringwheel(steeringwheel);
  builder_.add_handbrake(handbrake);
  builder_.add_accelerator(accelerator);
  builder_.add_brake(brake);
  builder_.add_clutch(clutch);
  return builder_.Finish();
}

flatbuffers::Offset<CtrlRawData> CreateCtrlRawData(flatbuffers::FlatBufferBuilder &_fbb, const CtrlRawDataT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ControlDataT : public flatbuffers::NativeTable {
  typedef ControlData TableType;
  std::unique_ptr<Rcd::VehicleCtrlCmd> vehicleCmd{};
  std::unique_ptr<Rcd::LightCtrlCmd> lightCmd{};
};

inline bool operator==(const ControlDataT &lhs, const ControlDataT &rhs) {
  return
      (lhs.vehicleCmd == rhs.vehicleCmd) &&
      (lhs.lightCmd == rhs.lightCmd);
}

inline bool operator!=(const ControlDataT &lhs, const ControlDataT &rhs) {
    return !(lhs == rhs);
}


struct ControlData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ControlDataT NativeTableType;
  typedef ControlDataBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ControlDataTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VEHICLECMD = 4,
    VT_LIGHTCMD = 6
  };
  const Rcd::VehicleCtrlCmd *vehicleCmd() const {
    return GetStruct<const Rcd::VehicleCtrlCmd *>(VT_VEHICLECMD);
  }
  Rcd::VehicleCtrlCmd *mutable_vehicleCmd() {
    return GetStruct<Rcd::VehicleCtrlCmd *>(VT_VEHICLECMD);
  }
  const Rcd::LightCtrlCmd *lightCmd() const {
    return GetStruct<const Rcd::LightCtrlCmd *>(VT_LIGHTCMD);
  }
  Rcd::LightCtrlCmd *mutable_lightCmd() {
    return GetStruct<Rcd::LightCtrlCmd *>(VT_LIGHTCMD);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Rcd::VehicleCtrlCmd>(verifier, VT_VEHICLECMD) &&
           VerifyField<Rcd::LightCtrlCmd>(verifier, VT_LIGHTCMD) &&
           verifier.EndTable();
  }
  ControlDataT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ControlDataT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ControlData> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ControlDataT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ControlDataBuilder {
  typedef ControlData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_vehicleCmd(const Rcd::VehicleCtrlCmd *vehicleCmd) {
    fbb_.AddStruct(ControlData::VT_VEHICLECMD, vehicleCmd);
  }
  void add_lightCmd(const Rcd::LightCtrlCmd *lightCmd) {
    fbb_.AddStruct(ControlData::VT_LIGHTCMD, lightCmd);
  }
  explicit ControlDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ControlData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ControlData>(end);
    return o;
  }
};

inline flatbuffers::Offset<ControlData> CreateControlData(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Rcd::VehicleCtrlCmd *vehicleCmd = 0,
    const Rcd::LightCtrlCmd *lightCmd = 0) {
  ControlDataBuilder builder_(_fbb);
  builder_.add_lightCmd(lightCmd);
  builder_.add_vehicleCmd(vehicleCmd);
  return builder_.Finish();
}

flatbuffers::Offset<ControlData> CreateControlData(flatbuffers::FlatBufferBuilder &_fbb, const ControlDataT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct StatusT : public flatbuffers::NativeTable {
  typedef Status TableType;
  uint8_t task = 0;
  uint8_t wheel = 0;
  uint8_t io = 0;
  uint8_t vehicle = 0;
};

inline bool operator==(const StatusT &lhs, const StatusT &rhs) {
  return
      (lhs.task == rhs.task) &&
      (lhs.wheel == rhs.wheel) &&
      (lhs.io == rhs.io) &&
      (lhs.vehicle == rhs.vehicle);
}

inline bool operator!=(const StatusT &lhs, const StatusT &rhs) {
    return !(lhs == rhs);
}


struct Status FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StatusT NativeTableType;
  typedef StatusBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return StatusTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASK = 4,
    VT_WHEEL = 6,
    VT_IO = 8,
    VT_VEHICLE = 10
  };
  uint8_t task() const {
    return GetField<uint8_t>(VT_TASK, 0);
  }
  bool mutate_task(uint8_t _task) {
    return SetField<uint8_t>(VT_TASK, _task, 0);
  }
  uint8_t wheel() const {
    return GetField<uint8_t>(VT_WHEEL, 0);
  }
  bool mutate_wheel(uint8_t _wheel) {
    return SetField<uint8_t>(VT_WHEEL, _wheel, 0);
  }
  uint8_t io() const {
    return GetField<uint8_t>(VT_IO, 0);
  }
  bool mutate_io(uint8_t _io) {
    return SetField<uint8_t>(VT_IO, _io, 0);
  }
  uint8_t vehicle() const {
    return GetField<uint8_t>(VT_VEHICLE, 0);
  }
  bool mutate_vehicle(uint8_t _vehicle) {
    return SetField<uint8_t>(VT_VEHICLE, _vehicle, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TASK) &&
           VerifyField<uint8_t>(verifier, VT_WHEEL) &&
           VerifyField<uint8_t>(verifier, VT_IO) &&
           VerifyField<uint8_t>(verifier, VT_VEHICLE) &&
           verifier.EndTable();
  }
  StatusT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(StatusT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Status> Pack(flatbuffers::FlatBufferBuilder &_fbb, const StatusT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct StatusBuilder {
  typedef Status Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_task(uint8_t task) {
    fbb_.AddElement<uint8_t>(Status::VT_TASK, task, 0);
  }
  void add_wheel(uint8_t wheel) {
    fbb_.AddElement<uint8_t>(Status::VT_WHEEL, wheel, 0);
  }
  void add_io(uint8_t io) {
    fbb_.AddElement<uint8_t>(Status::VT_IO, io, 0);
  }
  void add_vehicle(uint8_t vehicle) {
    fbb_.AddElement<uint8_t>(Status::VT_VEHICLE, vehicle, 0);
  }
  explicit StatusBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Status> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Status>(end);
    return o;
  }
};

inline flatbuffers::Offset<Status> CreateStatus(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t task = 0,
    uint8_t wheel = 0,
    uint8_t io = 0,
    uint8_t vehicle = 0) {
  StatusBuilder builder_(_fbb);
  builder_.add_vehicle(vehicle);
  builder_.add_io(io);
  builder_.add_wheel(wheel);
  builder_.add_task(task);
  return builder_.Finish();
}

flatbuffers::Offset<Status> CreateStatus(flatbuffers::FlatBufferBuilder &_fbb, const StatusT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ReqControlCmdT : public flatbuffers::NativeTable {
  typedef ReqControlCmd TableType;
  RcdControlCmd cmd = RcdControlCmd_Unknow;
};

inline bool operator==(const ReqControlCmdT &lhs, const ReqControlCmdT &rhs) {
  return
      (lhs.cmd == rhs.cmd);
}

inline bool operator!=(const ReqControlCmdT &lhs, const ReqControlCmdT &rhs) {
    return !(lhs == rhs);
}


struct ReqControlCmd FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ReqControlCmdT NativeTableType;
  typedef ReqControlCmdBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ReqControlCmdTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CMD = 4
  };
  RcdControlCmd cmd() const {
    return static_cast<RcdControlCmd>(GetField<uint8_t>(VT_CMD, 0));
  }
  bool mutate_cmd(RcdControlCmd _cmd) {
    return SetField<uint8_t>(VT_CMD, static_cast<uint8_t>(_cmd), 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CMD) &&
           verifier.EndTable();
  }
  ReqControlCmdT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ReqControlCmdT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ReqControlCmd> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ReqControlCmdT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ReqControlCmdBuilder {
  typedef ReqControlCmd Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_cmd(RcdControlCmd cmd) {
    fbb_.AddElement<uint8_t>(ReqControlCmd::VT_CMD, static_cast<uint8_t>(cmd), 0);
  }
  explicit ReqControlCmdBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ReqControlCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ReqControlCmd>(end);
    return o;
  }
};

inline flatbuffers::Offset<ReqControlCmd> CreateReqControlCmd(
    flatbuffers::FlatBufferBuilder &_fbb,
    RcdControlCmd cmd = RcdControlCmd_Unknow) {
  ReqControlCmdBuilder builder_(_fbb);
  builder_.add_cmd(cmd);
  return builder_.Finish();
}

flatbuffers::Offset<ReqControlCmd> CreateReqControlCmd(flatbuffers::FlatBufferBuilder &_fbb, const ReqControlCmdT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ResponVehicleAuthT : public flatbuffers::NativeTable {
  typedef ResponVehicleAuth TableType;
  std::string imei{};
  CommonResult result = CommonResult_Fail;
};

inline bool operator==(const ResponVehicleAuthT &lhs, const ResponVehicleAuthT &rhs) {
  return
      (lhs.imei == rhs.imei) &&
      (lhs.result == rhs.result);
}

inline bool operator!=(const ResponVehicleAuthT &lhs, const ResponVehicleAuthT &rhs) {
    return !(lhs == rhs);
}


struct ResponVehicleAuth FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ResponVehicleAuthT NativeTableType;
  typedef ResponVehicleAuthBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ResponVehicleAuthTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IMEI = 4,
    VT_RESULT = 6
  };
  const flatbuffers::String *imei() const {
    return GetPointer<const flatbuffers::String *>(VT_IMEI);
  }
  flatbuffers::String *mutable_imei() {
    return GetPointer<flatbuffers::String *>(VT_IMEI);
  }
  CommonResult result() const {
    return static_cast<CommonResult>(GetField<uint8_t>(VT_RESULT, 0));
  }
  bool mutate_result(CommonResult _result) {
    return SetField<uint8_t>(VT_RESULT, static_cast<uint8_t>(_result), 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IMEI) &&
           verifier.VerifyString(imei()) &&
           VerifyField<uint8_t>(verifier, VT_RESULT) &&
           verifier.EndTable();
  }
  ResponVehicleAuthT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResponVehicleAuthT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ResponVehicleAuth> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ResponVehicleAuthT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResponVehicleAuthBuilder {
  typedef ResponVehicleAuth Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_imei(flatbuffers::Offset<flatbuffers::String> imei) {
    fbb_.AddOffset(ResponVehicleAuth::VT_IMEI, imei);
  }
  void add_result(CommonResult result) {
    fbb_.AddElement<uint8_t>(ResponVehicleAuth::VT_RESULT, static_cast<uint8_t>(result), 0);
  }
  explicit ResponVehicleAuthBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ResponVehicleAuth> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ResponVehicleAuth>(end);
    return o;
  }
};

inline flatbuffers::Offset<ResponVehicleAuth> CreateResponVehicleAuth(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> imei = 0,
    CommonResult result = CommonResult_Fail) {
  ResponVehicleAuthBuilder builder_(_fbb);
  builder_.add_imei(imei);
  builder_.add_result(result);
  return builder_.Finish();
}

inline flatbuffers::Offset<ResponVehicleAuth> CreateResponVehicleAuthDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *imei = nullptr,
    CommonResult result = CommonResult_Fail) {
  auto imei__ = imei ? _fbb.CreateString(imei) : 0;
  return Rcd::CreateResponVehicleAuth(
      _fbb,
      imei__,
      result);
}

flatbuffers::Offset<ResponVehicleAuth> CreateResponVehicleAuth(flatbuffers::FlatBufferBuilder &_fbb, const ResponVehicleAuthT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ResponTaskStopT : public flatbuffers::NativeTable {
  typedef ResponTaskStop TableType;
  uint16_t taskId = 0;
};

inline bool operator==(const ResponTaskStopT &lhs, const ResponTaskStopT &rhs) {
  return
      (lhs.taskId == rhs.taskId);
}

inline bool operator!=(const ResponTaskStopT &lhs, const ResponTaskStopT &rhs) {
    return !(lhs == rhs);
}


struct ResponTaskStop FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ResponTaskStopT NativeTableType;
  typedef ResponTaskStopBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ResponTaskStopTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASKID = 4
  };
  uint16_t taskId() const {
    return GetField<uint16_t>(VT_TASKID, 0);
  }
  bool mutate_taskId(uint16_t _taskId) {
    return SetField<uint16_t>(VT_TASKID, _taskId, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TASKID) &&
           verifier.EndTable();
  }
  ResponTaskStopT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResponTaskStopT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<ResponTaskStop> Pack(flatbuffers::FlatBufferBuilder &_fbb, const ResponTaskStopT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResponTaskStopBuilder {
  typedef ResponTaskStop Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_taskId(uint16_t taskId) {
    fbb_.AddElement<uint16_t>(ResponTaskStop::VT_TASKID, taskId, 0);
  }
  explicit ResponTaskStopBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ResponTaskStop> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ResponTaskStop>(end);
    return o;
  }
};

inline flatbuffers::Offset<ResponTaskStop> CreateResponTaskStop(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t taskId = 0) {
  ResponTaskStopBuilder builder_(_fbb);
  builder_.add_taskId(taskId);
  return builder_.Finish();
}

flatbuffers::Offset<ResponTaskStop> CreateResponTaskStop(flatbuffers::FlatBufferBuilder &_fbb, const ResponTaskStopT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SendRemoteEstopT : public flatbuffers::NativeTable {
  typedef SendRemoteEstop TableType;
  uint8_t estop = 0;
};

inline bool operator==(const SendRemoteEstopT &lhs, const SendRemoteEstopT &rhs) {
  return
      (lhs.estop == rhs.estop);
}

inline bool operator!=(const SendRemoteEstopT &lhs, const SendRemoteEstopT &rhs) {
    return !(lhs == rhs);
}


struct SendRemoteEstop FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SendRemoteEstopT NativeTableType;
  typedef SendRemoteEstopBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SendRemoteEstopTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ESTOP = 4
  };
  uint8_t estop() const {
    return GetField<uint8_t>(VT_ESTOP, 0);
  }
  bool mutate_estop(uint8_t _estop) {
    return SetField<uint8_t>(VT_ESTOP, _estop, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ESTOP) &&
           verifier.EndTable();
  }
  SendRemoteEstopT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SendRemoteEstopT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SendRemoteEstop> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SendRemoteEstopT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SendRemoteEstopBuilder {
  typedef SendRemoteEstop Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_estop(uint8_t estop) {
    fbb_.AddElement<uint8_t>(SendRemoteEstop::VT_ESTOP, estop, 0);
  }
  explicit SendRemoteEstopBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SendRemoteEstop> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SendRemoteEstop>(end);
    return o;
  }
};

inline flatbuffers::Offset<SendRemoteEstop> CreateSendRemoteEstop(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t estop = 0) {
  SendRemoteEstopBuilder builder_(_fbb);
  builder_.add_estop(estop);
  return builder_.Finish();
}

flatbuffers::Offset<SendRemoteEstop> CreateSendRemoteEstop(flatbuffers::FlatBufferBuilder &_fbb, const SendRemoteEstopT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CtrlRawDataT *CtrlRawData::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CtrlRawDataT>(new CtrlRawDataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CtrlRawData::UnPackTo(CtrlRawDataT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = clutch(); _o->clutch = _e; }
  { auto _e = brake(); _o->brake = _e; }
  { auto _e = accelerator(); _o->accelerator = _e; }
  { auto _e = handbrake(); _o->handbrake = _e; }
  { auto _e = steeringwheel(); _o->steeringwheel = _e; }
}

inline flatbuffers::Offset<CtrlRawData> CtrlRawData::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CtrlRawDataT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCtrlRawData(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<CtrlRawData> CreateCtrlRawData(flatbuffers::FlatBufferBuilder &_fbb, const CtrlRawDataT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CtrlRawDataT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _clutch = _o->clutch;
  auto _brake = _o->brake;
  auto _accelerator = _o->accelerator;
  auto _handbrake = _o->handbrake;
  auto _steeringwheel = _o->steeringwheel;
  return Rcd::CreateCtrlRawData(
      _fbb,
      _clutch,
      _brake,
      _accelerator,
      _handbrake,
      _steeringwheel);
}

inline ControlDataT *ControlData::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ControlDataT>(new ControlDataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ControlData::UnPackTo(ControlDataT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = vehicleCmd(); if (_e) _o->vehicleCmd = std::unique_ptr<Rcd::VehicleCtrlCmd>(new Rcd::VehicleCtrlCmd(*_e)); }
  { auto _e = lightCmd(); if (_e) _o->lightCmd = std::unique_ptr<Rcd::LightCtrlCmd>(new Rcd::LightCtrlCmd(*_e)); }
}

inline flatbuffers::Offset<ControlData> ControlData::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ControlDataT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateControlData(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ControlData> CreateControlData(flatbuffers::FlatBufferBuilder &_fbb, const ControlDataT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ControlDataT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _vehicleCmd = _o->vehicleCmd ? _o->vehicleCmd.get() : 0;
  auto _lightCmd = _o->lightCmd ? _o->lightCmd.get() : 0;
  return Rcd::CreateControlData(
      _fbb,
      _vehicleCmd,
      _lightCmd);
}

inline StatusT *Status::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<StatusT>(new StatusT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Status::UnPackTo(StatusT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = task(); _o->task = _e; }
  { auto _e = wheel(); _o->wheel = _e; }
  { auto _e = io(); _o->io = _e; }
  { auto _e = vehicle(); _o->vehicle = _e; }
}

inline flatbuffers::Offset<Status> Status::Pack(flatbuffers::FlatBufferBuilder &_fbb, const StatusT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateStatus(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Status> CreateStatus(flatbuffers::FlatBufferBuilder &_fbb, const StatusT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const StatusT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _task = _o->task;
  auto _wheel = _o->wheel;
  auto _io = _o->io;
  auto _vehicle = _o->vehicle;
  return Rcd::CreateStatus(
      _fbb,
      _task,
      _wheel,
      _io,
      _vehicle);
}

inline ReqControlCmdT *ReqControlCmd::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ReqControlCmdT>(new ReqControlCmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ReqControlCmd::UnPackTo(ReqControlCmdT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cmd(); _o->cmd = _e; }
}

inline flatbuffers::Offset<ReqControlCmd> ReqControlCmd::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ReqControlCmdT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateReqControlCmd(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ReqControlCmd> CreateReqControlCmd(flatbuffers::FlatBufferBuilder &_fbb, const ReqControlCmdT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ReqControlCmdT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cmd = _o->cmd;
  return Rcd::CreateReqControlCmd(
      _fbb,
      _cmd);
}

inline ResponVehicleAuthT *ResponVehicleAuth::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResponVehicleAuthT>(new ResponVehicleAuthT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResponVehicleAuth::UnPackTo(ResponVehicleAuthT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = imei(); if (_e) _o->imei = _e->str(); }
  { auto _e = result(); _o->result = _e; }
}

inline flatbuffers::Offset<ResponVehicleAuth> ResponVehicleAuth::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ResponVehicleAuthT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResponVehicleAuth(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ResponVehicleAuth> CreateResponVehicleAuth(flatbuffers::FlatBufferBuilder &_fbb, const ResponVehicleAuthT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ResponVehicleAuthT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _imei = _o->imei.empty() ? 0 : _fbb.CreateString(_o->imei);
  auto _result = _o->result;
  return Rcd::CreateResponVehicleAuth(
      _fbb,
      _imei,
      _result);
}

inline ResponTaskStopT *ResponTaskStop::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResponTaskStopT>(new ResponTaskStopT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResponTaskStop::UnPackTo(ResponTaskStopT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = taskId(); _o->taskId = _e; }
}

inline flatbuffers::Offset<ResponTaskStop> ResponTaskStop::Pack(flatbuffers::FlatBufferBuilder &_fbb, const ResponTaskStopT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResponTaskStop(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<ResponTaskStop> CreateResponTaskStop(flatbuffers::FlatBufferBuilder &_fbb, const ResponTaskStopT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const ResponTaskStopT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _taskId = _o->taskId;
  return Rcd::CreateResponTaskStop(
      _fbb,
      _taskId);
}

inline SendRemoteEstopT *SendRemoteEstop::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SendRemoteEstopT>(new SendRemoteEstopT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SendRemoteEstop::UnPackTo(SendRemoteEstopT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = estop(); _o->estop = _e; }
}

inline flatbuffers::Offset<SendRemoteEstop> SendRemoteEstop::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SendRemoteEstopT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSendRemoteEstop(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SendRemoteEstop> CreateSendRemoteEstop(flatbuffers::FlatBufferBuilder &_fbb, const SendRemoteEstopT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SendRemoteEstopT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _estop = _o->estop;
  return Rcd::CreateSendRemoteEstop(
      _fbb,
      _estop);
}

inline const flatbuffers::TypeTable *CtrlRawDataTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_SHORT, 0, -1 }
  };
  static const char * const names[] = {
    "clutch",
    "brake",
    "accelerator",
    "handbrake",
    "steeringwheel"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 5, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *VehicleCtrlCmdTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_BOOL, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8, 12, 16, 17, 18, 19, 20, 21, 22, 24 };
  static const char * const names[] = {
    "steeringWheelAngle",
    "throttlePedal",
    "brakePedal",
    "hydraulicBrake",
    "retarderCtrl",
    "exhuastBrake",
    "parkCtrl",
    "bucketCtrl",
    "shiftCtrl",
    "eStop",
    "loadingCtrl"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 11, type_codes, nullptr, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *LightCtrlCmdTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    LightActionTypeTable
  };
  static const int64_t values[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
  static const char * const names[] = {
    "left",
    "right",
    "lowBeam",
    "heighBeam",
    "rotatingWarningLight",
    "speaker",
    "frontFog",
    "frontStatus",
    "side",
    "rearPosition",
    "emergency",
    "brake",
    "back",
    "rearStatus"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 14, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ControlDataTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    Rcd::VehicleCtrlCmdTypeTable,
    Rcd::LightCtrlCmdTypeTable
  };
  static const char * const names[] = {
    "vehicleCmd",
    "lightCmd"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *StatusTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, -1 }
  };
  static const char * const names[] = {
    "task",
    "wheel",
    "io",
    "vehicle"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 4, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ReqControlCmdTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    RcdControlCmdTypeTable
  };
  static const char * const names[] = {
    "cmd"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ResponVehicleAuthTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_UCHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    CommonResultTypeTable
  };
  static const char * const names[] = {
    "imei",
    "result"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *ResponTaskStopTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "taskId"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *SendRemoteEstopTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_UCHAR, 0, -1 }
  };
  static const char * const names[] = {
    "estop"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace Rcd

#endif  // FLATBUFFERS_GENERATED_RCD_RCD_H_
